CREATE DATABASE customer_shopping_behavior;
USE customer_shopping_behavior;

CREATE TABLE customers(
Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
Age INT,
Gender ENUM('Male', 'Female'),
Item_Purchased VARCHAR(50),
Category VARCHAR(50),
Purchase_Amount_USD INT,
Location VARCHAR(50),
Size TEXT,
Color VARCHAR(50),
Season VARCHAR(50),
Review_Rating DECIMAL(5,20),
Subscription_Status TEXT,
Shipping_Type VARCHAR(100),
Discount_Applied TEXT,
Promo_Code_Used TEXT,
Previous_Purchases INT,
Payment_Method VARCHAR(50),
Frequency_of_Purchases VARCHAR(100)
);


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(Purchase_Amount_USD) AS revenue FROM customers 
GROUP BY gender ;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT Customer_ID, Purchase_Amount_USD FROM customers WHERE Discount_Applied ='Yes' 
AND Purchase_Amount_USD > (SELECT AVG(Purchase_Amount_USD) FROM customers);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT Item_Purchased, ROUND(AVG(Review_Rating),2) AS Average_Product_Rating FROM customers 
GROUP BY Item_Purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT Shipping_Type, ROUND(AVG(Purchase_Amount_USD),2) AS avg_purchase FROM customers
WHERE Shipping_Type IN ('standard' , 'Express')
GROUP BY Shipping_Type ;
 

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT Subscription_Status,
	COUNT(Customer_id) AS Total_Customers,
	ROUND(AVG(Purchase_Amount_USD),2) Avg_purchase,
	SUM(Purchase_Amount_USD) AS Total_Revenue
FROM customers
GROUP BY Subscription_Status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT Item_Purchased,
		ROUND(100*SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS Discount_Rate 
	FROM customers 
    GROUP BY Item_Purchased
    ORDER BY Discount_Rate DESC
    LIMIT 5;
            

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT Subscription_Status, COUNT(Customer_ID) AS Repeat_Customers FROM customers 
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;


-- Q10. What is the revenue contribution of each age group? 
SELECT Age_Group,
		SUM(Purchase_Amount_USD) AS total_revenue
        FROM customers 
GROUP BY Age_Group
ORDER BY total_revenue DESC;

SELECT * FROM customers